name: "Publish Module to PowerShell Gallery"

on:
  release:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v2
        with:
          # Create module sub-directory for publish-powershell-module-action
          path: ${{ github.event.repository.name }}

      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          NuGetApiKey: ${{ secrets.API_KEY }}
